CREATE TABLE TB_CLIENT(
	CLIENT_ID INT IDENTITY (1,1) PRIMARY KEY,
	CLIENT_NAME VARCHAR (30),
	CLIENT_ADDRESS VARCHAR(30),
	CLIENT_OTHERADDRESS VARCHAR (30),
	CLIENT_INDUSTRIES VARCHAR (30),
	CLIENT_ID_DELIVERY VARCHAR (30),
	CLIENT_POSITION VARCHAR(30),
)

INSERT INTO TB_CLIENT (CLIENT_NAME, CLIENT_ADDRESS, CLIENT_OTHERADDRESS, CLIENT_INDUSTRIES,CLIENT_ID_DELIVERY, CLIENT_POSITION) 
VALUES('PT. Bank BCA','Menara BCA','-','Banking','ACA-01-SQA-1234','Java Developer'), ('PT. Bank Danamon','Kebon Sirih','Menara danamon','Banking','ACA-01-SQA-1341',' .NET Developer')

CREATE TABLE TB_SKILL (
		SKILL_ID INT IDENTITY (1,1) PRIMARY KEY,
		SKILL_NAME VARCHAR(30)
)

INSERT INTO TB_SKILL (SKILL_NAME) VALUES('C#.NET'),('VB.NET'),('PHP'),('Java'),('PYTHON')