



CREATE TABLE TB_CANDIDATE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CANDIDATE_ID VARCHAR(30),
	CANDIDATE_NAME VARCHAR(30),
	CANDIDATE_BIRTH DATE, 
	CANDIDATE_PLACEBIRTH VARCHAR(30),
	CANDIDATE_AGE INT,
	CANDIDATE_MARITALSTATUS VARCHAR(20),
	CANDIDATE_SEX VARCHAR (10),
	CANDIDATE_RELIGION VARCHAR(10),
	CANDIDATE_ETNIC VARCHAR(10),
	CANDIDATE_CITY VARCHAR (30),
	CANDIDATE_PROVINCE VARCHAR(10),
	CANDIDATE_CURRENT_ADDRESS VARCHAR (75),
	CANDIDATE_KTP_NUMBER BIGINT,
	CANDDIATE_NPWP_NUMBER BIGINT,
	CANDIDATE_HOMENUMBER INT,
	CANDIDATE_PHONENUMBER INT,
	CANDIDATE_EMAIL VARCHAR(50),
	CANDIDATE_CV TEXT,
	CANDIDATE_PHOTO IMAGE,
	CANDIDATE_CURRENT_SALARY BIGINT,
	CANDIDATE_EXPECTED_SALARY BIGINT,
	CANDIDATE_SCHOOL_NAME VARCHAR(50),
	CANDIDATE_SCHOOL_MAJOR VARCHAR(50),
	CANDIDATE_SCHOOL_DEGREE VARCHAR(10),
	CANDIDATE_SCHOOL_GPA FLOAT, 
	
)


	 

CREATE TABLE TB_SKILL_SET_JOBEXPERIENCED (
	SKILL_SET_ID VARCHAR (5) PRIMARY KEY,
	SKILL_SET_NAME VARCHAR (20),
)

create table TB_JOB_EXPERIENCED (
	JOBEXPERIENCED_ID VARCHAR (5) PRIMARY KEY,
	JOBEXPERIENCED_POSITION VARCHAR (20),
	JOBEXPERIENCED_PERIOD DATETIME,
	JOBEXPERIENCED_LAST_SALARY BIGINT,
	JOBEXPERIENCED_JOBDESC VARCHAR(500),
	SKILL_SET_ID VARCHAR (5) FOREIGN KEY REFERENCES TB_SKILL_SET_JOBEXPERIENCED(SKILL_SET_ID),
	CANDIDATE_ID INT FOREIGN KEY REFERENCES TB_CANDIDATE(ID),
)

CREATE TABLE TB_BENEFIT(
	BENEFIT_ID VARCHAR (5) PRIMARY KEY,
	BENEFIT_NAME VARCHAR (20),
	)


CREATE TABLE TB_BENEFIT_JOBEXPERIENCE(
	BENEFIT_JE_ID INT IDENTITY(1,1) PRIMARY KEY,
	BENEFIT_ID VARCHAR(5) FOREIGN KEY REFERENCES TB_BENEFIT(BENEFIT_ID),
	JOBEXPERIENCED_ID VARCHAR(5) FOREIGN KEY REFERENCES TB_JOB_EXPERIENCED(JOBEXPERIENCED_ID)

) 