
CREATE TABLE TB_JOB_POSITION(
		JOBPOSITION_ID INT IDENTITY(1,1) PRIMARY KEY,
		JOBPOSITION_NAME VARCHAR(30),
		JOBPOSITION_NOTES VARCHAR(500)
)


INSERT INTO TB_JOB_POSITION(JOBPOSITION_NAME) VALUES('C#.NET'),('VB.NET'),('PHP'),('Java'),('PYTHON')