
create TABLE TB_GENDER (
	GENDER_ID INT IDENTITY (1,1) PRIMARY KEY,
	GENDER_NAME VARCHAR (10),
)

INSERT INTO TB_GENDER (GENDER_NAME) VALUES('Pria'), ('Wanita')

CREATE TABLE TB_MARITALSTATUS(
	MARITALSTATUS_ID INT IDENTITY(10,1) PRIMARY KEY,
	MARITALSTATUS_NAME VARCHAR(15),
)

INSERT INTO TB_MARITALSTATUS (MARITALSTATUS_NAME) VALUES ('Menikah'), ('Belum Menikah')


create table TB_RELIGION(
	RELIGION_ID INT IDENTITY (100, 10) PRIMARY KEY,
	RELIGION_NAME VARCHAR (15),
)

INSERT INTO TB_RELIGION(RELIGION_NAME) VALUES ('Hindu'), ('Buddha'), ('Katholik'), ('Islam'), ('Kristen'), ('Konghucu'), ('Lain-Lain')

CREATE TABLE TB_CANDIDATE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CANDIDATE_ID VARCHAR(30),
	CANDIDATE_NAME VARCHAR(30),
	CANDIDATE_BIRTH DATE, 
	CANDIDATE_PLACEBIRTH VARCHAR(30),
	CANDIDATE_AGE INT,
	CANDIDATE_ETNIC VARCHAR(30),
	CANDIDATE_CITY VARCHAR (30),
	CANDIDATE_PROVINCE VARCHAR(30),
	CANDIDATE_CURRENT_ADDRESS VARCHAR (75),
	CANDIDATE_KTP_NUMBER BIGINT,
	CANDDIATE_NPWP_NUMBER BIGINT,
	CANDIDATE_HOMENUMBER INT,
	CANDIDATE_PHONENUMBER INT,
	CANDIDATE_EMAIL VARCHAR(50),
	CANDIDATE_CV TEXT,
	CANDIDATE_PHOTO IMAGE,
	CANDIDATE_CURRENT_SALARY BIGINT,
	CANDIDATE_EXPECTED_SALARY BIGINT,
	CANDIDATE_APPLIED_POSITION INT FOREIGN KEY REFERENCES TB_JOB_POSITION(JOBPOSITION_ID),
	CANDIDATE_SCHOOL_NAME VARCHAR(50),
	CANDIDATE_SCHOOL_MAJOR VARCHAR(50),
	CANDIDATE_SCHOOL_DEGREE VARCHAR(10),
	CANDIDATE_SCHOOL_GPA FLOAT, 
	GENDER_ID INT FOREIGN KEY REFERENCES TB_GENDER(GENDER_ID),
	MARITALSTATUS_ID INT FOREIGN KEY REFERENCES TB_MARITALSTATUS(MARITALSTATUS_ID),
	RELIGION_ID INT FOREIGN KEY REFERENCES TB_RELIGION(RELIGION_ID)
	
)


INSERT INTO TB_CANDIDATE (CANDIDATE_ID, CANDIDATE_NAME, CANDIDATE_BIRTH, CANDIDATE_PLACEBIRTH, CANDIDATE_AGE,CANDIDATE_ETNIC, CANDIDATE_CITY, CANDIDATE_PROVINCE, CANDIDATE_CURRENT_ADDRESS, CANDIDATE_KTP_NUMBER, CANDDIATE_NPWP_NUMBER, CANDIDATE_HOMENUMBER, CANDIDATE_PHONENUMBER, CANDIDATE_EMAIL, CANDIDATE_CURRENT_SALARY, CANDIDATE_EXPECTED_SALARY,CANDIDATE_APPLIED_POSITION, CANDIDATE_SCHOOL_NAME, CANDIDATE_SCHOOL_MAJOR, CANDIDATE_SCHOOL_DEGREE, CANDIDATE_SCHOOL_GPA, GENDER_ID, MARITALSTATUS_ID, RELIGION_ID) 

values('C001','Muhammad Andhika Kurniawan','2000/05/22','Jakarta',19 ,'Jawa','Jakarta Timur','DKI Jakarta','Jl. apake No.12',569845676,54677865425, 09872,981238, 'muhammadandhika@gmail.com', 2500000, 4000000, 1, 'SMK Negeri 4 jakarta', 'Teknik Komputer dan Jaringan', 'SMK', 312 , 1, 11, 130), 

('C001','Muhammad Tri','2001/05/22','Jakarta',18 ,'Jawa','Jakarta Utara','DKI Jakarta','Jl. Oxford No.12',985132584,54678665425, 09872,981238, 'muhammadtri@gmail.com', 2500000, 4000000, 2, 'SMK Perguruan Cikini', 'Teknik Komputer dan Jaringan', 'SMK', 300 , 1, 11, 130),

('C001','Teguh Triprasetya','2002/01/25','Jakarta',17 ,'Jawa','Jakarta Utara','DKI Jakarta','Jl. Perjuangan No.12',3173687532546,54678665485, 09872,981238, 'teguhtriprasetya@gmail.com', 2500000, 4000000, 2, 'SMK Negeri 36 Jakarta', 'Teknik Komputer dan Jaringan', 'SMK', 329 , 1, 11, 130)-- 



CREATE TABLE TB_SKILL_SET_JOBEXPERIENCED (
	SKILL_SET_ID VARCHAR (5) PRIMARY KEY,
	SKILL_SET_NAME VARCHAR (20),
)

INSERT INTO TB_SKILL_SET_JOBEXPERIENCED(SKILL_SET_ID,SKILL_SET_NAME)VALUES('SJE01','C#'),('SJE02','VB.NET'),('SJE03','Java'),('SJE04','PHP'),('SJE05','PYTHON'),('SJE06','NODEJS')



create table TB_JOB_EXPERIENCED (
	JOBEXPERIENCED_ID VARCHAR (5) PRIMARY KEY,
	JOBEXPERIENCED_POSITION VARCHAR (20),
	JOBEXPERIENCED_PERIOD DATETIME,
	JOBEXPERIENCED_LAST_SALARY BIGINT,
	JOBEXPERIENCED_JOBDESC VARCHAR(500),
	CANDIDATE_ID INT FOREIGN KEY REFERENCES TB_CANDIDATE(ID),
)

DROP TABLE TB_JOB_EXPERIENCED

INSERT INTO TB_JOB_EXPERIENCED (JOBEXPERIENCED_ID, JOBEXPERIENCED_POSITION, JOBEXPERIENCED_PERIOD, JOBEXPERIENCED_LAST_SALARY, JOBEXPERIENCED_JOBDESC, CANDIDATE_ID) VALUES ('JE001', 'Application Developer', '2018/10/25 - 2019/12/25',5000000 ,'Membuat aplikasi yang dipesan oleh client dan juga mengembangkan aplikasi yang sudah ada',1 ), ('JE002', 'PHP PROGRAMMING', '2018/10/25 - 2019/12/25', 5600000 ,'Membuat aplikasi yang dipesan oleh client dan juga mengembangkan aplikasi yang sudah ada' 2)


CREATE TABLE TB_SKILLSET_JOBEXP(
	SKILLSET_JOBEXP_ID INT IDENTITY(1,1) PRIMARY KEY,
	SKILLSET_ID VARCHAR (5) FOREIGN KEY REFERENCES TB_SKILL_SET_JOBEXPERIENCED(SKILL_SET_ID),
	JOBEXPERIENCED_ID VARCHAR(5) FOREIGN KEY REFERENCES TB_JOB_EXPERIENCED(JOBEXPERIENCED_ID)
)

INSERT INTO TB_SKILLSET_JOBEXP(SKILLSET_ID, JOBEXPERIENCED_ID) VALUES('SJE01', 'JE001'),('SJE02', 'JE002')('SJE03', 'JE003')('SJE04', 'JE004')('SJE04', 'JE001')

--DIKREASIKAN SESUKA HATI YAH. BEBAS CUMAN DUMMY

CREATE TABLE TB_BENEFIT(
	BENEFIT_ID VARCHAR (5) PRIMARY KEY,
	BENEFIT_NAME VARCHAR (20),
	)

INSERT INTO TB_BENEFIT(BENEFIT_ID,BENEFIT_NAME) VALUES('B01','THR'),('BO2','BONUS AKHIR BULAN'),('B03','BONUS AKHIR TAHUN'),('B04','BPJS'),('B05','ASURANSI SWASTA')

CREATE TABLE TB_BENEFIT_JOBEXPERIENCE(
	BENEFIT_JE_ID INT IDENTITY(1,1) PRIMARY KEY,
	BENEFIT_ID VARCHAR(5) FOREIGN KEY REFERENCES TB_BENEFIT(BENEFIT_ID),
	JOBEXPERIENCED_ID VARCHAR(5) FOREIGN KEY REFERENCES TB_JOB_EXPERIENCED(JOBEXPERIENCED_ID)
) 

INSERT INTO TB_BENEFIT_JOBEXPERIENCE(BENEFIT_ID, JOBEXPERIENCED_ID) VALUES ('B01', 'J002'), ('B03', 'J002'), ('B03', 'J001')

