
CREATE TABLE TB_CLIENT_STATE(
	STATECLIENT_ID INT IDENTITY (200,1) PRIMARY KEY,
	STATECLIENT_NAME VARCHAR (10),
)

INSERT INTO TB_CLIENT_STATE (STATECLIENT_NAME) VALUES ('Ok'), ('Interview'), ('Drop')



CREATE TABLE TB_DELIVERY_HISTORY (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	DELIVERY_ID VARCHAR(8),
	CANDIDATE_ID INT FOREIGN KEY REFERENCES TB_CANDIDATE(ID),
	POSITION INT FOREIGN KEY REFERENCES TB_JOB_POSITION(JOBPOSITION_ID),
	STATE_CLIENT INT FOREIGN KEY REFERENCES TB_CLIENT_STATE(STATECLIENT_ID),
	LAST_PIC INT FOREIGN KEY REFERENCES TB_USER(USER_ID),
	PROCESS_DATE DATE,
	DELIVERY_CLIENT INT FOREIGN KEY REFERENCES TB_CLIENT(ID),
	STATE_ID VARCHAR (5) FOREIGN KEY REFERENCES TB_STATE (STATE_ID),
	LAST_UPDATE DATE,
	SELECTION_ID INT FOREIGN KEY REFERENCES TB_SELECTION_HISTORY(ID),
	NOTES TEXT,
)